### ISSUE TITLE
FP: "Warn when emphasis (including strong), instead of a heading, introduces a paragraph."

### ISSUE THREAD

**Issue by StingyJack** [codacy/codacy-remark-lint#266]
* **I'm submitting a ...**
 bug report - apologies if this is not the correct place to report. We are using Codacy, and this linter was enabled for a repo I just added and its flagging something it shouldn't be. I dont have anywhere else in the Codacy UI to report a problem, and it didnt seem right to report this on remark-lint's GH first. 

* **Summary**
This is either a defect or a bad rule that shouldn't be enabled/exist. Given the following markdown...

``` markdown
### Tooth Care

_Its very important to remember_ to floss after brushing

```
The first sentence will generate the warning, but its not incorrect or even wrong to start a paragraph with this styling. 

## Why you ask?

_Sometimes its necessary_ to grab the readers attention.

### But also

**Because they need to see something important** before they continue reading

**Comment by franciscodua** [comment]
Hi @StingyJack 

As you said the rule is from remark-lint.
But we'll use this feedback the next time we review the patterns that are enabled by default. We appreciate this kind of feedback.

If this rule doesn't make sense for your project, you can disable it by going to "Code patterns" (on you left bar) > RemarkLint and uncheck the pattern you want to remove.

I'll close this issue since we're tackling the default part in a different context.
But if you still have questions regarding this feel free to re-open it
